server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATASOURCE_URL}
  application:
    name: kindergarten

king:
  jwt:
    secret: ${KING_JWT_SECRET}

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE