server:
  port: 8050

spring:
  application:
    name: kindergarten

  datasource:
    url: jdbc:postgresql://localhost:5432/kindergarten
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


king:
  jwt:
    secret: OK9SBV/0HRurtEw3umYg5pgTwzN97EBAylK0I4cJ+M0=

logging:
  level:
    root: INFO
#    org.springframework.data.mongodb.core: DEBUG