server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://mongo:PRHJgQPaSjvfwizYhvbIkyKXclrdwFYM@trolley.proxy.rlwy.net:41673/kindergarten
  application:
    name: kindergarten

king:
  jwt:
    secret: OK9SBV/0HRurtEw3umYg5pgTwzN97EBAylK0I4cJ+M0=

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE