server:
  port: 8050

spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/kindergarten"

  application:
    name: kindergarten

front:
  service:
    url: http://localhost:3000

king:
  jwt:
    secret: OK9SBV/0HRurtEw3umYg5pgTwzN97EBAylK0I4cJ+M0=

logging:
  level:
    root: INFO
#    org.springframework.data.mongodb.core: DEBUG