server:
  port: ${SERVER_PORT}

spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
  application:
    name: kindergarten

flag:
  dev: ${DEV_FLAG}

king:
  jwt:
    secret: OK9SBV/0HRurtEw3umYg5pgTwzN97EBAylK0I4cJ+M0=

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE